import { GenericProduct } from './dataStructures';

export const shirtData: GenericProduct[] = [
  {
    id: 0,
    productId: 0,
    name: '100T Shirt',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 1,
    productId: 1,
    name: 'Louisville Shirt',
    img: 'louisvilleShirt.JPEG',
    description: '',
  },
  {
    id: 2,
    productId: 2,
    name: '100T Long Sleeve Shirt',
    img: '100TLongSleeve.JPEG',
    description: '',
  },
  {
    id: 3,
    productId: 3,
    name: 'River City Shirt',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 4,
    productId: 4,
    name: 'River City Shirt',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 5,
    productId: 5,
    name: 'River City Shirt',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 6,
    productId: 6,
    name: 'River City Shirt',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 7,
    productId: 7,
    name: 'River City Shirt',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 8,
    productId: 8,
    name: 'River City Shirt',
    img: '100TShirt.JPEG',
    description: '',
  }
];
export const shoesData: GenericProduct[] = [
  {
    id: 0,
    productId: 0,
    name: '100T shoes',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 1,
    productId: 1,
    name: 'Louisville shoes',
    img: 'louisvilleShirt.JPEG',
    description: '',
  },
  {
    id: 2,
    productId: 2,
    name: '100T Long Sleeve shoes',
    img: '100TLongSleeve.JPEG',
    description: '',
  },
  {
    id: 3,
    productId: 3,
    name: 'River City shoes',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 4,
    productId: 4,
    name: 'River City shoes',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 5,
    productId: 5,
    name: 'River City shoes',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 6,
    productId: 6,
    name: 'River City shoes',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 7,
    productId: 7,
    name: 'River City shoes',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 8,
    productId: 8,
    name: 'River City shoes',
    img: '100TShirt.JPEG',
    description: '',
  }
];
export const bottomData: GenericProduct[] = [
  {
    id: 0,
    productId: 0,
    name: '100T bottom',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 1,
    productId: 1,
    name: 'Louisville bottom',
    img: 'louisvilleShirt.JPEG',
    description: '',
  },
  {
    id: 2,
    productId: 2,
    name: '100T Long Sleeve bottom',
    img: '100TLongSleeve.JPEG',
    description: '',
  },
  {
    id: 3,
    productId: 3,
    name: 'River City bottom',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 4,
    productId: 4,
    name: 'River City bottom',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 5,
    productId: 5,
    name: 'River City bottom',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 6,
    productId: 6,
    name: 'River City bottom',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 7,
    productId: 7,
    name: 'River City bottom',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 8,
    productId: 8,
    name: 'River City bottom',
    img: '100TShirt.JPEG',
    description: '',
  }
];
export const accessoriesData: GenericProduct[] = [
  {
    id: 0,
    productId: 0,
    name: '100T  accessories',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 1,
    productId: 1,
    name: 'Louisville accessories',
    img: 'louisvilleShirt.JPEG',
    description: '',
  },
  {
    id: 2,
    productId: 2,
    name: '100T Long Sleeve accessories',
    img: '100TLongSleeve.JPEG',
    description: '',
  },
  {
    id: 3,
    productId: 3,
    name: 'River City accessories',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 4,
    productId: 4,
    name: 'River City accessories',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 5,
    productId: 5,
    name: 'River City accessories',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 6,
    productId: 6,
    name: 'River City accessories',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 7,
    productId: 7,
    name: 'River City accessories',
    img: '100TShirt.JPEG',
    description: '',
  },
  {
    id: 8,
    productId: 8,
    name: 'River City accessories',
    img: '100TShirt.JPEG',
    description: '',
  }
];